roles:
  無職:
    x: 0
    y: 0
    z: 0
  商人:
    x: 0
    y: 0
    z: 0
  漁師:
    x: 0
    y: 0
    z: 0
  パン屋:
    x: 0
    y: 0
    z: 0
  電気工事士:
    x: 0
    y: 0
    z: 0
  冒険者:
    x: 0
    y: 0
    z: 0
  石工:
    x: 0
    y: 0
    z: 0
  鍛冶屋:
    x: 0
    y: 0
    z: 0

