deathPenalty:
  # y = min(base + percentage * (x - base), max) でデスペナルティが計算される
  base: 200 # デスペナルティの基本値
  percentage: 0.01 # デスペナルティの割合
  max: 2000 # デスペナルティの最大値
defaultRole: tutorial
neetRole: neet
notion: '{"text":"[クリックして説明書(Notion)を確認]","color":"gold","clickEvent":{"action":"open_url","value":"https://bit.ly/eco-tutorial"}}'
maxRole: 1
roles:
  tutorial:
    name: チュートリアル
    home:
      world: world_the_end
      x: 145
      y: 155
      z: -237
    color: AQUA
  neet:
    name: ニート
    home:
      world: world_the_end
      x: 262
      y: 103
      z: 94
    color: DARK_GRAY
  ryousi:
    name: 漁師
    home:
      world: world_the_end
      x: 296
      y: 158
      z: 12
    color: YELLOW
    potionEffects:
      - ==: PotionEffect
        effect: 26
        duration: 1200
        amplifier: 2
        ambient: true
        has-particles: false
        has-icon: true
  nougyou:
    name: 農業
    home:
      world: world_the_end
      x: 298
      y: 158
      z: -15
    color: LIGHT_PURPLE
    potionEffects:
      - ==: PotionEffect
        effect: 8
        duration: 1200
        amplifier: 2
        ambient: true
        has-particles: false
        has-icon: true
  isiku:
    name: 石工
    home:
      world: world_the_end
      x: 298
      y: 158
      z: -15
    color: GREEN
    potionEffects:
      - ==: PotionEffect
        effect: 5
        duration: 1200
        amplifier: 0
        ambient: true
        has-particles: false
        has-icon: true
  kikori:
    name: 木こり
    home:
      world: world_the_end
      x: 298
      y: 158
      z: -15
    color: GOLD
    potionEffects:
      - ==: PotionEffect
        effect: 3
        duration: 1200
        amplifier: 3
        ambient: true
        has-particles: false
        has-icon: true
  kaziya:
    name: 鍛冶屋
    home:
      world: world_the_end
      x: 296
      y: 158
      z: 30
    color: GRAY
  saihousi:
    name: 裁縫師
    home:
      world: world_the_end
      x: 297
      y: 158
      z: 21
    color: DARK_PURPLE
    potionEffects:
      - ==: PotionEffect
        effect: 1
        duration: 1200
        amplifier: 2
        ambient: true
        has-particles: false
        has-icon: true
  魔法研究員:
    name: 魔法研究員
    home:
      world: world_the_end
      x: 298
      y: 158
      z: -15
    color: WHITE
    potionEffects:
      - ==: PotionEffect
        effect: 11
        duration: 1200
        amplifier: 0
        ambient: true
        has-particles: false
        has-icon: true
