deathPenalty: 2000
defaultRole: tutorial
neetRole: ニート
notion: '{"text":"[クリックして説明書(Notion)を確認]","color":"gold","clickEvent":{"action":"open_url","value":"https://bit.ly/eco-tutorial"}}'
roles:
  tutorial:
    name: チュートリアル
    home:
      world: world_the_end
      x: 145
      y: 155
      z: -237
    color: AQUA
  ニート:
    name: ニート
    home:
      world: world_the_end
      x: 262
      y: 103
      z: 94
    color: DARK_GRAY
  漁師:
    name: 漁師
    home:
      world: world_the_end
      x: 298
      y: 158
      z: 12
    color: YELLOW
    potionEffects:
      - ==: PotionEffect
        effect: 26
        duration: 1200
        amplifier: 2
        ambient: true
        has-particles: false
        has-icon: true
  パン屋:
    name: パン屋
    home:
      world: world_the_end
      x: 298
      y: 158
      z: -6
    color: LIGHT_PURPLE
    potionEffects:
      - ==: PotionEffect
        effect: 8
        duration: 1200
        amplifier: 2
        ambient: true
        has-particles: false
        has-icon: true
  剣士:
    name: 剣士
    home:
      world: world_the_end
      x: 298
      y: 158
      z: 48
    color: GREEN
    potionEffects:
      - ==: PotionEffect
        effect: 5
        duration: 1200
        amplifier: 0
        ambient: true
        has-particles: false
        has-icon: true
  魔法使い:
    name: 魔法使い
    home:
      world: world_the_end
      x: 288
      y: 158
      z: 39
    color: GOLD
    potionEffects:
      - ==: PotionEffect
        effect: 3
        duration: 1200
        amplifier: 3
        ambient: true
        has-particles: false
        has-icon: true
  鍛冶屋:
    name: 鍛冶屋
    home:
      world: world_the_end
      x: 298
      y: 158
      z: 30
    color: GRAY
  裁縫師:
    name: 裁縫師
    home:
      world: world_the_end
      x: 298
      y: 158
      z: 21
    color: DARK_PURPLE
    potionEffects:
      - ==: PotionEffect
        effect: 1
        duration: 1200
        amplifier: 2
        ambient: true
        has-particles: false
        has-icon: true
  魔法研究員:
    name: 魔法研究員
    home:
      world: world_the_end
      x: 298
      y: 158
      z: 3
    color: WHITE
    potionEffects:
      - ==: PotionEffect
        effect: 11
        duration: 1200
        amplifier: 0
        ambient: true
        has-particles: false
        has-icon: true
