name: skyblock2
version: '${project.version}'
main: com.github.kumo0621.skyblock2.Skyblock2
api-version: '1.20'

depend:
  - Vault
  - LuckPerms

commands:
  setrole:
    permission: skyblock2.setrole
  warp:
    permission: skyblock2.warp
  notion:
    permission: skyblock2.notion

permissions:
  skyblock2.admin:
    default: op
  skyblock2.setrole:
    default: op
  skyblock2.warp:
    default: true
  skyblock2.notion:
    default: true
  skyblock2.tutorial:
    default: false
  skyblock2.ニート:
    default: false
  skyblock2.魔法使い:
    default: false
  skyblock2.裁縫師:
    default: false
  skyblock2.剣士:
    default: false
  skyblock2.漁師:
    default: false
  skyblock2.鍛冶屋:
    default: false
  skyblock2.魔法研究員:
    default: false
  skyblock2.パン屋:
    default: false
