name: skyblock2
version: '${project.version}'
main: com.github.kumo0621.skyblock2.Skyblock2
api-version: '1.20'
commands:
  setrole:
    aliases: skyblock2.command
    permission: skyblock2.command
  warp:
    aliases: skyblock2.command
    permission: skyblock2.command

permissions:
  skyblock2.admin:
    default: op
  skyblock2.command:
    default: true