name: skyblock2
version: '${project.version}'
main: com.github.kumo0621.skyblock2.Skyblock2
api-version: '1.20'

depend:
  - Vault
  - LuckPerms

commands:
  setrole:
    aliases: skyblock2.command
    permission: skyblock2.setrole
  warp:
    aliases: skyblock2.command
    permission: skyblock2.command

permissions:
  skyblock2.admin:
    default: op
  skyblock2.setrole:
    default: op
  skyblock2.command:
    default: true
  skyblock2.ニート:
    default: false
  skyblock2.石工:
    default: false
  skyblock2.裁縫師:
    default: false
  skyblock2.冒険者:
    default: false
  skyblock2.漁師:
    default: false
  skyblock2.鍛冶屋:
    default: false
  skyblock2.電気工事士:
    default: false
  skyblock2.パン屋:
    default: false
