name: skyblock2
version: '${project.version}'
main: com.github.kumo0621.skyblock2.Skyblock2
api-version: '1.20'
commands:
  setrole:
    aliases: notop
    permission: notop
  shop:
    aliases: setrole
    permission: setrole
  warp:
    aliases: notop
    permission: notop

permissions:
  setrole:
    default: op
  notop:
    default: true